### PR TITLE
Add docker cron container

### PR DESCRIPTION
**Pull request by MarcInthaamnouay**
- Fix generation of random number
- Fix wrong SQL query on temporary.go cron job
- Add logger definition to the cron
- Add logger container
- Remove environment variable on ```api``` services and use ```env_file``` instead
- Add crontab definition to the cron service

### CODE REVIEW

**Comment by kinok** [comment]
You'd better use https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by MarcInthaamnouay** [comment]
@kinok yes, this is plan in the next couples of future commits. For now I just only set up the cron in Docker. A config for each cron will be done for Kubernetes (maybe on Kubectl for local test too ?)

**Comment by kinok** [comment]
@MarcInthaamnouay, take a peek at https://kubernetes.io/docs/setup/minikube/
This should help with local environment.
FYI this comes along with docker for Mac, I think it just needs to be activated.

**Comment by MarcInthaamnouay** [comment]
@kinok thanks. Yes I have setup minikube and trying to use it in order to see if the jobs is working. So far maybe

**Comment by MarcInthaamnouay** [comment]
@kinok  thanks for your help !

**Pull request merged**
